name: Bug report
description: Report a reproducible bug in Akompani.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact steps to reproduce.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste console logs, errors, or screenshots.
      render: shell

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Chat mode
        - Canvas mode
        - Deploy mode
        - Settings
        - Docs
        - CI / GitHub Pages
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, browser, Bun version
      placeholder: macOS 15, Chrome 133, bun 1.3.3
    validations:
      required: true
